name: Continuous Publish on Docker Hub

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Build a Container Image
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          docker build --build-arg ENV_FILE=${{ secrets.ENV_FILE }} -t ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:${{ github.run_id }} .

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:${{ github.run_id }} ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:latest
