name: Continuous Publish on Docker Hub

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Create .env file
        run: echo "$ENV_FILE" > .env

      - name: Build a Container Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:${{ github.run_id }} .
          
      - name: Push Image to Docker hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:${{ github.run_id }} ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/stack-overblog-api:latest
